### ISSUE TITLE
ProtHint exited due to an error in command: grep Intron Spaln/spaln.gff > introns.gff

### ISSUE THREAD

**Issue by lfaller-zymergen** [gatech-genemark/ProtHint#15]
Hello,

I ran into the following error while running BRAKER2. However, since the issue seems to pop up while running ProtHint, I posted my question here. Please let me know if I should move this to the BRAKER2 issue tracker.

This is my error message:

`ProtHint exited due to an error in command: grep Intron Spaln/spaln.gff > introns.gff`

I think this grep command likely fails because my `Spaln/spaln.gff` file is empty.

I should note that this is happening when I run BRAKER2 on a small input dataset. I wanted to test things out so I am giving it just a portion of the genome of interest. I assume that maybe the input file doesn't have any introns because it's too small. 

I am curious, does this tool fail if the input genome sequence has no introns? 

Thanks for any insight!

Log:

```
Cmd: /root/ProtHint/bin/prothint.py --threads=1 --geneMarkGtf /data/braker_out3/GeneMark-ES/genemark.gtf /data/braker_out3/genome.fa /data/braker_out3/proteins.fa

[Mon Aug 31 18:14:55 2020] Skipping GeneMark-ES, using the supplied gene seeds file instead
[Mon Aug 31 18:14:55 2020] Translating gene seeds to proteins
[Mon Aug 31 18:14:55 2020] Translation of seeds finished
[Mon Aug 31 18:14:55 2020] Running DIAMOND
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: /data/braker_out3/proteins.fa
Opening the database file...  [0.006061s]
Loading sequences...  [0.001275s]
Masking sequences...  [0.006247s]
Writing sequences...  [5.5e-05s]
Hashing sequences...  [1.2e-05s]
Loading sequences...  [0.000523s]
Writing trailer...  [9e-06s]
Closing the input file...  [0.000404s]
Closing the database file...  [0.000997s]
Database hash = 1c808e3f9bc4e4567be9baae0fdf84f0
Processed 25 sequences, 25577 letters.
Total time = 0.015852s
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory:
Opening the database...  [0.002401s]
#Target sequences to report alignments for: 25
Opening the input file...  [0.001917s]
Opening the output file...  [0.000997s]
Loading query sequences...  [0.00131s]
Masking queries...  [0.003393s]
Building query seed set...  [0.000992s]
Algorithm: Double-indexed
Building query histograms...  [0.000432s]
Allocating buffers...  [2.8e-05s]
Loading reference sequences...  [0.000911s]
Building reference histograms...  [0.000557s]
Allocating buffers...  [1.6e-05s]
Initializing temporary storage...  [0.025931s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.000604s]
Building query index...  [0.000603s]
Building seed filter...  [0.000245s]
Searching alignments...  [0.000789s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [0.000638s]
Building query index...  [0.000694s]
Building seed filter...  [0.000223s]
Searching alignments...  [0.000852s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [0.000392s]
Building query index...  [0.000432s]
Building seed filter...  [0.000248s]
Searching alignments...  [0.000983s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [0.000802s]
Building query index...  [0.000509s]
Building seed filter...  [0.000243s]
Searching alignments...  [0.001009s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [0.000453s]
Building query index...  [0.000509s]
Building seed filter...  [0.000316s]
Searching alignments...  [0.000748s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [0.0005s]
Building query index...  [0.000624s]
Building seed filter...  [0.000309s]
Searching alignments...  [0.000832s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [0.000584s]
Building query index...  [0.000551s]
Building seed filter...  [0.000246s]
Searching alignments...  [0.000899s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [0.000483s]
Building query index...  [0.000476s]
Building seed filter...  [0.000272s]
Searching alignments...  [0.000721s]
Deallocating buffers...  [9e-06s]
Computing alignments...  [0.00435s]
Deallocating reference...  [5.3e-05s]
Loading reference sequences...  [0.000899s]
Deallocating buffers...  [9.2e-05s]
Deallocating queries...  [1.4e-05s]
Loading query sequences...  [0.000423s]
Closing the input file...  [0.00035s]
Closing the output file...  [0.000289s]
Closing the database file...  [0.000378s]
Deallocating taxonomy...  [1.2e-05s]
Total time = 0.067032s
Reported 0 pairwise alignments, 0 HSPs.
0 queries aligned.
[Mon Aug 31 18:14:55 2020] DIAMOND finished
[Mon Aug 31 18:14:55 2020] Preparing pairs for alignments
[Mon Aug 31 18:14:55 2020] Preparation of pairs finished
[Mon Aug 31 18:14:55 2020] Starting spliced alignment with spaln
[Mon Aug 31 18:14:55 2020] Loading alignment pairs into memory
[Mon Aug 31 18:14:55 2020] Pairs loaded. Number of pairs to align: 0
[Mon Aug 31 18:14:55 2020] Starting the alignments
[Mon Aug 31 18:14:55 2020] 0/0 (100%) pairs aligned
[Mon Aug 31 18:14:55 2020] Alignment of pairs finished
[Mon Aug 31 18:14:55 2020] Translating coordinates from local pair level to contig level
[Mon Aug 31 18:14:55 2020] Finished spliced alignment
[Mon Aug 31 18:14:55 2020] Processing the output
[Mon Aug 31 18:14:55 2020] error: ProtHint exited due to an error in command: grep Intron Spaln/spaln.gff > introns.gff
ERROR in file /opt/conda/bin/braker.pl at line 4973
Failed to execute /root/ProtHint/bin/prothint.py --threads=1 --geneMarkGtf /data/braker_out3/GeneMark-ES/genemark.gtf /data/braker_out3/genome.fa /data/braker_out3/proteins.fa!
```

**Comment by tomasbruna** [comment]
Hello @lfaller-zymergen,

thank you for this report, this is the right place for this issue.

The error is definitely caused by a small input data set. From the logs you shared, I see DIAMOND did not find any candidate homologous proteins for alignment (I suppose there are not many proteins in your input?).

I have recently fixed this border case in this commit https://github.com/gatech-genemark/ProtHint/commit/19c6c950f1dbc416d986e8484afddae4bb207703, can you let me know if you are running the latest versions of ProtHint? In the new version, instead of this error, the result should be an empty output file (which might cause errors further downstream in BRAKER though).

If you want to test BRAKER with small inputs, I recommend to take a look here https://github.com/Gaius-Augustus/BRAKER#example-data and run the `test2.sh` test.

Best,
Tomas

**Comment by lfaller-zymergen** [comment]
Thanks for the feedback!

I've been running ProtHint v2.4.0. It looks like the commit you linked to above is tagged with v2.5.0.

I took a look at the `test2.sh` you suggested and, unfortunately, it runs into an error as well:

```
#*********
#*********
# WARNING: Number of reliable training genes is low (59). Recommended are at least 600 genes
#*********
ERROR in file /opt/BRAKER-2.1.5/scripts/braker.pl at line 7996
Failed to execute: /usr/bin/python3 /opt/Augustus/scripts/fix_in_frame_stop_codon_genes.py -g /opt/BRAKER-2.1.5/example/tests/test2/genome.fa -t /opt/BRAKER-2.1.5/example/tests/test2/augustus.hints.gtf -b /opt/BRAKER-2.1.5/example/tests/test2/bad_genes.lst -o augustus.hints_fix_ifs_ -s Sp_2 -m on --UTR off --print_utr off -a /opt/Augustus/config -C /opt/cdbfasta -A /opt/Augustus/bin -S /opt/Augustus/scripts -H /opt/BRAKER-2.1.5/example/tests/test2/hintsfile.gff -e /opt/BRAKER-2.1.5/scripts/cfg/ep.cfg  > /opt/BRAKER-2.1.5/example/tests/test2/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /opt/BRAKER-2.1.5/example/tests/test2/errors/fix_in_frame_stop_codon_genes_augustus.hints.err
```

The contents of the error file are:

```bash
$> cat /opt/BRAKER-2.1.5/example/tests/test2/errors/fix_in_frame_stop_codon_genes_augustus.hints.err
Traceback (most recent call last):
  File "/opt/Augustus/scripts/fix_in_frame_stop_codon_genes.py", line 737, in <module>
    for ifs_line in ifs_handle:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)
```

This looks to be an issue now with Augustus, though, not with ProtHint.

**Comment by tomasbruna** [comment]
This error is indeed an AUGUSTUS problem, there is a solution here https://github.com/Gaius-Augustus/BRAKER/issues/254

**Comment by tomasbruna** [comment]
Also, the test examples in BRAKER went through many improvements recently, I recommend to get the latest version of BRAKER (from the master branch) and ProtHint (v2.5.0) to get the latest test set.

**Comment by lfaller-zymergen** [comment]
Thank you for the quick feedback! This was really helpful -- I did have to adjust the locale to make this error go away. 

What also helped: grabbing the newest BRAKER source from github (I had been working with your last `release` which was from February 2020).
